---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Cloning PGBlitz"
      git:
        repo: "https://github.com/hawk2g/Install"
        dest: "/pg/pgstage"
        version: "v1"
        force: yes
